/**
 * Opens a print-friendly window for PDF export via browser print dialog.
 */
export function printHtmlDocument(title: string, bodyHtml: string) {
  const win = window.open('', '_blank', 'noopener,noreferrer,width=800,height=1000');
  if (!win) return;
  win.document.write(`
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${title}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; color: #1a1a1a; padding: 40px; max-width: 720px; margin: 0 auto; }
    h1 { font-size: 24px; margin: 0 0 8px; }
    .gold { color: #8b6b3f; }
    .meta { font-size: 12px; color: #71717a; margin-bottom: 24px; }
    .hero { width: 100%; height: 200px; object-fit: cover; margin: 16px 0 24px; }
    section { margin-bottom: 20px; border-top: 1px solid #f2f2f0; padding-top: 16px; }
    h2 { font-size: 11px; text-transform: uppercase; letter-spacing: 0.12em; color: #a1a1aa; margin: 0 0 8px; }
    p { font-size: 14px; line-height: 1.6; margin: 0; }
  </style>
</head>
<body>${bodyHtml}</body>
</html>`);
  win.document.close();
  win.focus();
  setTimeout(() => {
    win.print();
  }, 400);
}

export interface PresentationSummaryExport {
  projectName: string;
  clientName: string;
  date: string;
  advisor: string;
  summary: string;
  notes?: string;
  heroImageUrl?: string;
}

export function exportPresentationSummary(data: PresentationSummaryExport) {
  const hero = data.heroImageUrl
    ? `<img class="hero" src="${data.heroImageUrl}" alt="${data.projectName}" />`
    : '';
  printHtmlDocument(
    `${data.projectName} — Summary`,
    `
    <h1>${data.projectName}</h1>
    <p class="meta">${data.clientName} · ${data.date} · Advisor: ${data.advisor}</p>
    ${hero}
    <section><h2>Summary</h2><p>${data.summary}</p></section>
    ${data.notes ? `<section><h2>Advisor notes</h2><p>${data.notes}</p></section>` : ''}
    <p class="meta" style="margin-top:32px">Generated by Propley Sales CRM</p>
  `
  );
}

export interface ClientSummaryExport {
  clientName: string;
  city: string;
  advisor: string;
  dealStage: string;
  nextPresentation?: string;
  notesSnippet?: string;
}

export function exportClientSummary(data: ClientSummaryExport) {
  printHtmlDocument(
    `${data.clientName} — Client summary`,
    `
    <h1>${data.clientName}</h1>
    <p class="meta">${data.city} · ${data.advisor} · Stage: <span class="gold">${data.dealStage}</span></p>
    ${data.nextPresentation ? `<section><h2>Next presentation</h2><p>${data.nextPresentation}</p></section>` : ''}
    ${data.notesSnippet ? `<section><h2>Recent notes</h2><p>${data.notesSnippet}</p></section>` : ''}
  `
  );
}
